### ISSUE TITLE
Add links around supplied info

### ISSUE THREAD

**Issue by Haroenv** [reimertz/lagom#4]
When running the cli, it asks for your site, twitter, GitHub, and those are added in the created slides, but they aren't links. I think it'd be nice if they are also available as links by default.

**Comment by Haroenv** [comment]
I've seen that it should be added around https://github.com/reimertz/lagom/blob/master/src/index.html#L17, but I couldn't find what you're using to render the moustaches, so I don't know how to add variables in attributes.

**Comment by reimertz** [comment]
yeah, this needs some rework.. :)
This is how I do it now https://github.com/reimertz/lagom/blob/master/src/bin/lagom-create.js#L35

**Comment by Haroenv** [comment]
`<a href="https://twitter.com/{{twitter}}">{{twitter}}</a>` would work then?

**Comment by reimertz** [comment]
yep, that would do it, the only issue is that if the user doesn't enter anything, you'd still get a link without any content.

i think a better thing here is to introduce a template renderer.

**Comment by reimertz** [comment]
so we could do something similar to this
```
{{ if twitter }}
  <a href="https://twitter.com/{{twitter}}">{{twitter}}</a>
{{ endif }}
```

**Comment by Haroenv** [comment]
Yep, that's what I remark in #5 too, now all of those variables always get rendered (link or not)
