### ISSUE TITLE
implement lagom deploy

### ISSUE THREAD

**Issue by reimertz** [reimertz/lagom#6]

**Comment by reimertz** [comment]
probably just going to wrap this: https://github.com/zeit/now-serve

**Comment by Haroenv** [comment]
https://github.com/zeit/now-client is what will be needed to used, however this asks for an api key (which you can get [here](https://zeit.co/account#api-tokens).

However it seems that ns doesn't depend on now-client. Maybe it uses some other way?

**Comment by reimertz** [comment]
@Haroenv I also created this a while back that deploys static content as a gist.
http://github.com/reimertz/gistploy

I just need to iterate on since it doesn't work anymore, probably due to rawgit/github changing something in their api.

Also, gistploy would be better since it's free and to be honest, zeit/now-serve is actually booting up a node service for each individual deployment, which I think would be a huge waste of energy since lagom is strictly static.

**Comment by reimertz** [comment]
@Haroenv deploy should work in 0.3.0. please let me know if you find any issues. <3

**Comment by Haroenv** [comment]
Nice. I'll check it out

**Comment by reimertz** [comment]
I will close this now, feel like it's legit now. :)

**Comment by Haroenv** [comment]
```
$ lagom deploy
◩         lagom: deploy
◩         status: loading index.html
◩         status: loading lagom.js
◩         status: processing external css lagom.css
◩         status: loading lagom.css
◩         status: creating gist
◩         status: shortening url
◩         error: code is not defined
$ lagom deploy index.html 
◩         lagom: deploy
◩         status: loading index.html
◩         status: loading lagom.js
◩         status: processing external css lagom.css
◩         status: loading lagom.css
◩         status: creating gist
◩         status: shortening url
◩         error: code is not defined
$ lagom deploy qsdf
◩         lagom: deploy
◩         error: qsdf doesn't exist
```

How do I enter a code, and what is it?

**Comment by reimertz** [comment]
fuck

**Comment by Haroenv** [comment]
in https://github.com/reimertz/lagom/blob/master/src/bin/lagom-deploy.js#L52 you're printing `code`, but that's not defined. Maybe it's `shortenedURL` instead?

**Comment by reimertz** [comment]
@Haroenv fixed now in v0.4.0. Sorry about that. refactored some code and forgot to fix variable rename at one spo..... exaclty! 💯

**Comment by reimertz** [comment]
```
$ lagom deploy
◩         lagom: deploy
◩         status: loading index.html
◩         status: loading lagom.js
◩         status: processing external css lagom.css
◩         status: loading lagom.css
◩         status: creating gist
◩         status: shortening url
◩         deployed: http://lagom.hook.io/?c=vPRgE

```

**Comment by Haroenv** [comment]
```
lagom deploy
◩         lagom: deploy
◩         status: loading index.html
◩         status: loading lagom.js
◩         status: processing external css lagom.css
◩         status: loading lagom.css
◩         status: creating gist
◩         status: shortening url
◩         deployed: http://lagom.hook.io/?c=vPR2p
```

perfect now!
